name: lm_labs_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  extreme_flutter_lints:
    git:
      url: git@github.com:glemartret/extreme_flutter_lints.git
      ref: v0.0.2
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
